BEGIN;

--- Par prévention, on commence par supprimer des tables qui porteraient déjà ce nom
--- ps: on rajoute la suppression de la table tag afin de supprimer la table de ce nom 
--- qui a pu être créée lors de l'atelier

DROP TABLE IF EXISTS "TRAINER", "TEAM", "POKEMON", "TYPE", "POKEMON_HAS_TYPE";


--- Table "TRAINER" qui contiendra les informations de nos dresseurs

CREATE TABLE "TRAINER" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"firstname" TEXT NOT NULL DEFAULT "No Firstame",
"lastname" TEXT NOT NULL DEFAULT "No Lastname",
"email" text NOT NULL,
"password" text NOT NULL,
"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" timestamptz
);

CREATE TABLE "TEAM" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"title" TEXT NOT NULL DEFAULT "No Title",
"position" SMALLINT NOT NULL DEFAULT 0,
--- Ici c'est la clé étrangère qui lie TEAM à TRAINER 
--- ON DELETE CASCADE, on dit que si jamais on supprime un élément de TRAINER
--- On supprime également l'élément de de Team ici lié à la clé étrangère.
"trainer_id" INTEGER NOT NULL REFERENCES "TRAINER"("id") ON DELETE CASCADE, 
"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" timestamptz
);

CREATE TABLE "POKEMON" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"pokemon" TEXT NOT NULL,
"nickname" TEXT NOT NULL DEFAULT "No Nickame",
"level" INTEGER NOT NULL DEFAULT "No Level",
"image" TEXT NOT NULL DEFAULT "No Image",
"position" SMALLINT NOT NULL DEFAULT 0,
--- Ici pareil, clé étrangère qui lie POKEMON à TEAM
"team_id" INTEGER NOT NULL REFERENCES "TEAM"("id") ON DELETE CASCADE,
"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" timestamptz
);

CREATE TABLE "TYPE" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" TEXT NOT NULL,
"color" TEXT NOT NULL DEFAULT "#FFF",
"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" timestamptz
);


CREATE TABLE "POKEMON_HAS_TYPE" (
"pokemon_id" INTEGER NOT NULL REFERENCES "POKEMON"("id") ON DELETE CASCADE,
"type_id" INTEGER NOT NULL REFERENCES "TYPE"("id") ON DELETE CASCADE,
"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

--- On passe au Seeding, c'est-à-dire, à l'ajout de données dans nos tables

INSERT INTO "TRAINER"("firstname", "lastname", "email", "password") VALUES
('Sacha', 'Ketchum', 'sachaketchum@bourg-palette.kanto', 'pikachu4ever'),
('Regis', 'Chen', 'regischen@bourg-palette.kanto', 'evoli4ever'),
('Nowaki', 'Blueberry', 'blueberrynowaki@vergazon.hoenn', 'shaymin4ever')
;

INSERT INTO "TEAM"("title", "trainer_id") VALUES
('Pikachu Fiesta', 1),
('Evoli-Pride', 2),
('Solo Noctali', 2),
('Shaymin & Compagnie', 3),
('Giratina GGWP', 3)
;

INSERT INTO "POKEMON"("pokemon_name", "nickname", "level", "image", "position", "team_id") VALUES
('Pikachu', 'Pikachou', 1345, './img/pikachu.png', 1, 1),
('Evoli', 'Evolichou', 9999, './img/evoli.png', 1, 2),
('Aquali', 'Aquachou', 543, './img/aquali.png', 2, 2),
('Voltali', 'Voltachou', 10, './img/voltali.png', 3, 2),
('Pyroli', 'Pyrochou', 100, './img/pyroli.png', 4, 2),
('Mentali', 'Mentachou', 134, './img/mentali.png', 5, 2),
('Phylalli', 'Phyllachou', 404, './img/phylalli.png', 6, 2),
('Noctali', 'Noctoutou', 500, './img/noctali.png', 1, 3),
('Shaymin', 'Shaymin', 8888888,'./img/shaymin', 1, 4),
('Ectoplasma', 'Ectopla-sama', 10000,'./img/ectoplasma', 2, 4),
('Ronflex', 'Rompichbébou', 99999,'./img/ronflex', 3, 4),
('Pyrax', 'Pyrachou', 1234,'./img/pyrax', 4, 4),
('Charmilly', 'GateauMiam', 3456,'./img/charmilly', 5, 4),
('Giratina', 'Girachou', 999999999, './img/giratina', 1, 5)
;

INSERT INTO "TYPE"("name","color") VALUES
('Eletrik', "#E6FF33"),
('Normal', "#FCFAEF"),
('Eau', "#1F97F5"),
('Feu', "#F51F1F"),
('Psy', "#E51FF5"),
('Plante', "#1BD53A"),
('Ténèbre', "#000000"),
('Vol', "#DCDCDC"),
('Spectre', "#7900EA"),
('Insecte', "#4FF5B1"),
('Fée', "#FFAAFA"),
('Dragon', "#4913F3")
;

INSERT INTO "POKEMON_HAS_TYPE"("pokemon_id", "type_id")
(1, 1),
(2, 2),
(3, 3),
(4, 1),
(5, 4),
(6, 5),
(7, 6),
(8, 7),
(9, 6),
(9, 8),
(10, 9),
(11, 2),
(12, 4),
(12, 10),
(13, 11),
(14, 12),
(14, 7)
;

COMMIT; 